### ISSUE TITLE
update underlying code to automatically convert types

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/blocks-to-code-old#2]
for Scratch:
- the mathematical operators `--- + ---` should convert both operands to integers by default, and catch any errors (because of parsing)
- similarly, `join --- and ---` should convert both operands to string

**Comment by user-74** [comment]
Note: the + operator still has issue putting in text, check where type checking is for this and allow it

**Comment by user-74** [comment]
Solved in code generation by applying `parseInt()` wherever needed
