### ISSUE TITLE
ask and wait -> statement + output

### ISSUE THREAD

**Issue by user-74** [MajeedKazemi/blocks-to-code-old#8]
Currently the ask and wait block returns the answer as the output.

To mimic Scratch this block should be converted to a separate output block as the answer, and the ask block converted to a statement.

**Comment by MajeedKazemi** [comment]
@user-74 have you find any solutions to implement this?

**Comment by user-74** [comment]
I've grabbed the blocks over from Scratch, but I don't think it came with code generation. I will look into that and see if its possible, otherwise I'll attempt to write some myself

**Comment by user-74** [comment]
Using `var` to declare variable allows them to be brought to the top.
Using the answer block before ask has a value of undefined.

For answer, use the variable set in var.
